// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using steam_server_command_center.Models;

#nullable disable

namespace steam_server_command_center.Migrations
{
    [DbContext(typeof(CommandCenterContext))]
    [Migration("20240308043511_add_steam_app_id_to_enabled_servers")]
    partial class add_steam_app_id_to_enabled_servers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("steam_server_command_center.Models.ConfigurationItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("steam_server_command_center.Models.EnabledServer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerID")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameServerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SteamAppID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("EnabledServers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("steam_server_command_center.Models.GameServer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SteamAppID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("GameServers");
                });
#pragma warning restore 612, 618
        }
    }
}
